### ISSUE TITLE
Get home page 

### ISSUE THREAD

**Issue by Isha-121** [MSTC-DA-IICT/Hacktoberfest22-Blog-App#3]
Write a basic code to just get the home page for router

**Comment by ykodwani01** [comment]
I would like to work on this issue @Isha-121

**Comment by Isha-121** [comment]
Yes you can @ykodwani01  . But the folder node blog app is currently not visible I am trying on it. So just wait for one more day. But surely, you are assigned this task.

**Comment by Isha-121** [comment]
Now resolved, You can start working on it!

**Comment by ykodwani01** [comment]
> Now resolved, You can start working on it!

I have made a pull request , can you review it @Isha-121
