### ISSUE TITLE
Post blog 

### ISSUE THREAD

**Issue by Isha-121** [MSTC-DA-IICT/Hacktoberfest22-Blog-App#4]
Write a code for posting blog let say blogger wants to post his blog ,then you need to write code for blogger so that on clicking post button blog will be posted

**Comment by dhairya-create** [comment]
I would like to work on this issue @Isha-121

**Comment by Isha-121** [comment]
Yes you can @dhairya-create . But the folder node blog app is currently not visible I am trying on it. So just wait for one more day. But surely, you are assigned this task.

**Comment by Isha-121** [comment]
Now resolved, You can start working on it!

**Comment by dhairya-create** [comment]
@Isha-121 I have member rights and I have the rights to merge, and there are no conflicts, so can I merge my PR?

**Comment by Isha-121** [comment]
Just wait I will do that
